todo/todo/api/urls.py
from rest_framework import routers
from .views import TarefaViewSet
from django.urls import path, include

router = routers.DefaultRouter()
router.register("tarefas", TarefaViewSet)

app_name = "api"

urlpatterns = [
    path('', include(router.urls))
]

todo/todo/app/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('tarefas.urls', namespace="tarefas")),
    path('api/', include('api.urls', namespace="api")),

]

todo/todo/tarefas/urls.py
from django.urls import path
from .views import listar, adicionar, deletar, editar, ver


app_name = "tarefas"

urlpatterns = [
    path('', listar, name="listar"),
    path('inserir/', adicionar, name='adicionar'),
    path("<int:tarefa_pk>/deletar", deletar, name="deletar"),
    path("<int:tarefa_pk>/editar/", editar, name="editar"),
    path('<int:tarefa_id>/ver/', ver, name='ver')
]

todo/todo/api/models.py
from django.db import models

# Create your models here.

todo/todo/tarefas/models.py
from django.db import models


class Tarefa(models.Model):
    TAREFA_STATUS = [
        ("concluido", "Concluído"),
        ("nao_concluido", "Não Concluído")
    ]
    titulo = models.CharField("Titulo", max_length=200)
    conteudo = models.TextField("Descrição")
    status = models.CharField("Status", default="nao_concluido", choices=TAREFA_STATUS, max_length=15)

todo/todo/tarefas/forms.py
from django import forms
from .models import Tarefa


class TarefaForm(forms.ModelForm):
    class Meta:
        model = Tarefa
        fields = ("titulo", "conteudo", "status")

todo/todo/api/views.py
from rest_framework import viewsets
from tarefas.models import Tarefa
from .serializers import TarefaSerializer


class TarefaViewSet(viewsets.ModelViewSet):
    queryset = Tarefa.objects.all()
    serializer_class = TarefaSerializer

todo/todo/tarefas/views.py
from django.shortcuts import render, reverse, redirect, get_object_or_404

from .models import Tarefa
from .forms import TarefaForm


def listar(request):
    tarefas = Tarefa.objects.all()
    return render(request, 'tarefas/list.html', {'tarefas': tarefas})

def ver(request, tarefa_id):
    tarefa = Tarefa.objects.get(id=tarefa_id)
    return render(request, 'tarefas/detalhes.html', {'tarefa': tarefa})


def editar(request, tarefa_pk):
    tarefa = get_object_or_404(Tarefa.objects, pk=tarefa_pk)
    form = TarefaForm(request.POST or None, instance=tarefa)

    if form.is_valid():
        form.save()
        return redirect(reverse("tarefas:listar"))

    return render(request, "tarefas/edit.html", context={"tarefa": tarefa, "form": form})


def adicionar(request):
    form = TarefaForm(request.POST or None)

    if form.is_valid():
        form.save()
        return redirect(reverse("tarefas:listar"))

    return render(request, "tarefas/add.html", context={"form": form})

def deletar(request, tarefa_pk):
    tarefa = get_object_or_404(Tarefa.objects, pk=tarefa_pk)

    tarefa.delete()

    return redirect(reverse("tarefas:listar"))

todo/todo/tarefas/templates/tarefas/add.html
{% load static %}

<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <title>ADICIONAR</title>

    <link rel="stylesheet" href="{% static 'css/bootstrap.min.css' %}">

        <div class="container d-flex justify-content-between">
            <a href="{% url 'tarefas:listar' %}" class="navbar-brand d-flex align-items-center">
                <strong>ADICIONAR</strong>
            </a>
        </div>
</head>

<body>

<main role="main" class="container">

    <div class="container">
        <form method=POST>
            {% csrf_token %}

            <label class="h4">Nome</label>
            <input type="text" class="form-control" {{ form.titulo }}

            <label class="h4">Conteudo</label>
            <input type="text" class="form-control" {{ form.conteudo }}

            <label class="h4">Concluído?</label>
            <select type="text" class="form-control" {{ form.status }}

            <a href="{% url 'tarefas:adicionar' %}">
                <button style="color:black">Adicionar</button>
            </a>
        </form>

    </div>

</main>

<script src="http://ajax.googleapis.com/ajax/libs/jquery/3.5.1/jquery.min.js"></script>
<script src="{% static 'js/bootstrap.min.js' %}"></script>

</body>
</html>

todo/todo/tarefas/templates/tarefas/detalhes.html
{% extends 'base.html' %}
{% block content %}

    <div class="container">
        <h2>{{ tarefa.titulo }} - {{ tarefa.get_status_display }}</h2>
    </div>
    <div class="container">
        <h3> Descrição </h3>
    </div>
    <div class="container">
        <p>{{ tarefa.conteudo }}</p>
    </div>

{% endblock %}

todo/todo/tarefas/templates/tarefas/edit.html
{% load static %}

<!DOCTYPE html>
<html lang="pt-br">

<head>
    <meta charset="UTF-8">
    <title>EDITAR</title>

    <link rel="stylesheet" href="{% static 'css/bootstrap.min.css' %}">

        <div class="container d-flex justify-content-between">
            <a href="{% url 'tarefas:listar' %}" class="navbar-brand d-flex align-items-center">
                <strong>EDITAR</strong>
            </a>
    </div>
</head>

<body>

<main role="main" class="container">

    <div class="container">
        <form method=POST>
            {% csrf_token %}

            <label class="h4">Nome</label>
            <div><input type="text" class="form-control"{{ form.titulo }}</div>

            <label class="h4">Conteudo</label>
            <textarea class="form-control" {{ form.conteudo }}

            <label class="h4">Concluido?</label>
            <div><select type="text" class="form-control" {{ form.status }}</div>

                <a href="{% url 'tarefas:adicionar' %}">
                    <button style="color:black">Editar Tarefa</button>
                </a>
        </form>

    </div>

</main>

<script src="http://ajax.googleapis.com/ajax/libs/jquery/3.5.1/jquery.min.js"></script>
<script src="{% static 'js/bootstrap.min.js' %}"></script>

</body>
</html>

todo/todo/tarefas/templates/tarefas/list.html
{% extends 'base.html' %}

{% block content %}

    <div class="row">
    {% for tarefa in tarefas%}
            <div class="container">

        <div class="row">
            <div class="col">
                    <svg aria-label="Placeholder: Thumbnail"
                         preserveAspectRatio="xMidYMid slice" focusable="false"><title></title>
                        <rect width="100%" height="100%"/>
                        <text x="50%" y="50%" fill="#eceeef" dy=".3em">{{ tarefa.titulo }}</text>
                    </svg>

                    <div class="card-body">
                        <div class="d-flex justify-content-between align-items-center">
                            <div class="btn-group">
                                <a href="{% url 'tarefas:ver' tarefa.id %}"><button class="btn btn-sm btn-outline-secondary">Ver</button></a>
                                <a href="{% url 'tarefas:editar' tarefa.pk %}" ><button type="button" class="btn btn-sm btn-outline-secondary">Editar</button></a>
                                <a href="{% url 'tarefas:deletar' tarefa.pk %}" ><button type="button" class="btn btn-sm btn-outline-secondary">Deletar</button></a>
                            
                            <p>{{ tarefa.get_status_display }}</p>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>

    {% endfor %}
    </div>

{% endblock %}

todo/todo/templates/base.html
{% load static %}

<!DOCTYPE html>
<html lang="pt-br">
<head>
    <meta charset="UTF-8">
    <title>INICIO</title>

    <link rel="stylesheet" href="{% static 'css/bootstrap.min.css' %}">


        <div class="container d-flex justify-content-between">
            <a href="{% url 'tarefas:listar' %}" class="navbar-brand d-flex align-items-center">
                <strong>INICIO</strong>
            </a>
        </div>

</head>
<body>


<main role="main">

    <section >
        <div class="container">
            <h1>Tarefas</h1>
            <p>
                <a href="{% url 'tarefas:adicionar' %}">ADD</a>
            </p>
        </div>
    </section>




</main>

{% block content %}{% endblock %}

<script src="http://ajax.googleapis.com/ajax/libs/jquery/3.5.1/jquery.min.js"></script>
<script src="{% static 'js/bootstrap.min.js' %}"></script>

</body>
</html>